/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultRouteImport } from './routes/result'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InterviewIndexRouteImport } from './routes/interview/index'
import { Route as InterviewInterviewIdIndexRouteImport } from './routes/interview/$interviewId/index'
import { Route as InterviewInterviewIdSummaryRouteImport } from './routes/interview/$interviewId/summary'

const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewIndexRoute = InterviewIndexRouteImport.update({
  id: '/interview/',
  path: '/interview/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewInterviewIdIndexRoute =
  InterviewInterviewIdIndexRouteImport.update({
    id: '/interview/$interviewId/',
    path: '/interview/$interviewId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InterviewInterviewIdSummaryRoute =
  InterviewInterviewIdSummaryRouteImport.update({
    id: '/interview/$interviewId/summary',
    path: '/interview/$interviewId/summary',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/result': typeof ResultRoute
  '/interview/': typeof InterviewIndexRoute
  '/interview/$interviewId/summary': typeof InterviewInterviewIdSummaryRoute
  '/interview/$interviewId/': typeof InterviewInterviewIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/result': typeof ResultRoute
  '/interview': typeof InterviewIndexRoute
  '/interview/$interviewId/summary': typeof InterviewInterviewIdSummaryRoute
  '/interview/$interviewId': typeof InterviewInterviewIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/result': typeof ResultRoute
  '/interview/': typeof InterviewIndexRoute
  '/interview/$interviewId/summary': typeof InterviewInterviewIdSummaryRoute
  '/interview/$interviewId/': typeof InterviewInterviewIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/result'
    | '/interview/'
    | '/interview/$interviewId/summary'
    | '/interview/$interviewId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/result'
    | '/interview'
    | '/interview/$interviewId/summary'
    | '/interview/$interviewId'
  id:
    | '__root__'
    | '/'
    | '/result'
    | '/interview/'
    | '/interview/$interviewId/summary'
    | '/interview/$interviewId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResultRoute: typeof ResultRoute
  InterviewIndexRoute: typeof InterviewIndexRoute
  InterviewInterviewIdSummaryRoute: typeof InterviewInterviewIdSummaryRoute
  InterviewInterviewIdIndexRoute: typeof InterviewInterviewIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/': {
      id: '/interview/'
      path: '/interview'
      fullPath: '/interview/'
      preLoaderRoute: typeof InterviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$interviewId/': {
      id: '/interview/$interviewId/'
      path: '/interview/$interviewId'
      fullPath: '/interview/$interviewId/'
      preLoaderRoute: typeof InterviewInterviewIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$interviewId/summary': {
      id: '/interview/$interviewId/summary'
      path: '/interview/$interviewId/summary'
      fullPath: '/interview/$interviewId/summary'
      preLoaderRoute: typeof InterviewInterviewIdSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResultRoute: ResultRoute,
  InterviewIndexRoute: InterviewIndexRoute,
  InterviewInterviewIdSummaryRoute: InterviewInterviewIdSummaryRoute,
  InterviewInterviewIdIndexRoute: InterviewInterviewIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
